mc-sema/bin_descend/bin_descend.cpp
=> Adding support for specifying output file in bin_descend

mc-sema/bin_descend/CFG_pb2.py, mc-sema/bin_descend/get_cfg.py, mc-sema/binary_common/CFG.proto, mc-sema/cfgToLLVM/JumpTables.cpp, mc-sema/cfgToLLVM/JumpTables.h, mc-sema/cfgToLLVM/x86Helpers.cpp, mc-sema/cfgToLLVM/x86Helpers.h, mc-sema/cfgToLLVM/x86Instrs_Branches.cpp, mc-sema/cfgToLLVM/x86_64Helpers.cpp, mc-sema/peToCFG/CFG.proto, mc-sema/peToCFG/peToCFG.cpp, mc-sema/peToCFG/peToCFG.h
Support for GCC generated jump tables in PIE binaries.
Better ELF thunk detection (more direct API calls, fewer `do_call_value`)
=> Support for Offset Tables

mc-sema/cfgToLLVM/raiseX86.h, mc-sema/cfgToLLVM/raiseX86_64.cpp
Added and modified codes to check xmm0-7 registers in the case of linux x64 calling convention
=> Support floating point arguments of linux x64 calling convention

mc-sema/bin_descend/get_cfg.py, mc-sema/cfgToLLVM/raiseX86.h, mc-sema/cfgToLLVM/x86Instrs_ADD.cpp, mc-sema/cfgToLLVM/x86Instrs_CMPTEST.cpp, mc-sema/cfgToLLVM/x86Instrs_SSE.cpp, mc-sema/cfgToLLVM/x86Instrs_SUB.cpp, mc-sema/cfgToLLVM/x86Instrs_bitops.cpp, mc-sema/std_defs/linux.txt
IDA sometimes gets jump table size wrong. Attempt to detect and workaround the issue.
=> IDA Jump tables bug workaround

mc-sema/cfgToLLVM/x86Instrs_Misc.cpp
Adds initial CPUID instruction support.
=> Adding CPUID support

docs/McsemaWalkthrough.md
=> Add walkthrough document

tools/mcsema_disass/__main__.py, tools/mcsema_disass/ida/disass.py
* Use full paths for extended arguments to the disassembler script
=> Fix mcsema-disass checks

docs/McsemaWalkthrough.md
=> Document walkthrough

mcsema/CFG/CFG.cpp
=> Initialize `m` to nullptr

tools/llvm_38_to_35.sh
* Handle floating point loads in update script
=> Handle floating types in 3.8 => 3.5 conversion script

README.md, docs/UsingLibFuzzer.md, tests/libFuzzer/.gitignore, tests/libFuzzer/README.md, tests/libFuzzer/buildFuzzer.sh, tests/libFuzzer/driver.cc, tests/libFuzzer/fuzzme.cc
Closes #131 and provides a cool demo
=> Show how to use mcsema with libFuzzer

docs/DEFFileGeneration.md, docs/McsemaWalkthrough.md, tools/generate_def_file.py
=> + script to print DEF file

README.md
* Add FAQs on IDA and student contributions
=> Add FAQ Entries on IDA and Student Contributions

CMakeLists.txt, bootstrap.osx.sh
Resolves #189 
Tests "pass" but that's because the test runner skips them all.
```bash
$ python tests/integration_test.py
testHello (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be disabled.~
~
ok
testStringPool (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be disabled.~
~
ok
testlodsb (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be disabled.~
~
ok
testls (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be disabled.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ok
testswitch (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be disabled.~
~
ok
testxz (__main__.LinuxTest) ... WARNING: Running linux tests on Darwin. Some tests will be …
```
=> macOS support

tools/mcsema_disass/defs/linux.txt
Adds ACL related definitions to std_defs
=> Adds ACL definitions

tools/build_idapython.sh
Added a script to build a Python interpreter suitable for IDA Pro when running under linux x64.
The script also bundles SetupTools and PIP, so that third party libraries can be easily installed.
=> Added a script to build a replacement for the IDA's built-in Python.

bootstrap.sh, docs/CommonErrors.md, docs/DEFFileGeneration.md, docs/LifeOfAnInstruction.md, docs/Limitations.md, mcsema/Arch/Arch.cpp, mcsema/Arch/X86/Lift.cpp, mcsema/Arch/X86/Runtime/print_ELF_32_linux.cpp, mcsema/Arch/X86/Runtime/print_PE_32_windows.cpp, mcsema/Arch/X86/Runtime/print_PE_64_windows.cpp, mcsema/Arch/X86/Semantics/INCDECNEG.cpp, mcsema/Arch/X86/Semantics/SSE.cpp, mcsema/Arch/X86/Semantics/String.cpp, mcsema/Arch/X86/Semantics/flagops.h, mcsema/Arch/X86/Util.h, mcsema/BC/Lift.cpp, mcsema/BC/Util.cpp, mcsema/BC/Util.h, tests/linux/amd64/config.json, tests/linux/amd64/expected_outputs.json, tools/mcsema_disass/defs/linux.txt, tools/mcsema_disass/ida/get_cfg.py
Please be careful w/ this set. No testing was performed.
offhand, the most interesting appear to be:
`InitADFeatures`
`recursive option`
=> Spelling fixes

.appveyor.yml, CMakeLists.txt, bootstrap.bat, bootstrap.sh, mcsema/Arch/Arch.cpp, mcsema/Arch/Arch.h, tests/integration_test.py, tools/mcsema_disass/defs/windows.txt, tools/mcsema_disass/ida/get_cfg.py
* Escape CMAKE_BINARY_PATH also
* win32 => windows for mcsema-lift expected arch, to match mcsema-disass
* Fix data and underscores for externals
* IDA 6.7 compatibility in get_cfg.py
=> More windows fixes

tools/build_idapython.sh
This fix allows plugins to use PyQt correctly.
=> tools/IDAPython builder: Added SIP (required by PyQt)

package.sh
Resurrect old package.sh to create deb/rpm.
=> resurrect packaging script

mcsema/Arch/X86/Semantics/ShiftRoll.cpp, mcsema/Arch/X86/Semantics/fpu.cpp
* ROR64rCL
* FCOMPP
* COMP_FST0r
* COM_FST0r
=> Support ROR64CL and more floating point comparisons

tools/mcsema_disass/ida/get_cfg.py
The commit is in response to [issue 308](https://github.com/trailofbits/mcsema/issues/308)
=> IDA in Batch mode does not recognize printf declaration as external code.

mcsema/BC/Function.cpp, mcsema/BC/Instruction.cpp, mcsema/BC/Segment.cpp, mcsema/CFG/CFG.cpp, tools/mcsema_disass/ida/get_cfg.py, tools/mcsema_disass/ida/refs.py, tools/mcsema_disass/ida/table.py, tools/mcsema_disass/ida/util.py
@kumarak When you have the time, can you run this through the jmeter suite to make sure there are no regressions?
=> Fixues issue #321.

README.md
=> fix missing link

mcsema/CFG/CFG.cpp, mcsema/CFG/CFG.h, mcsema/CFG/CFG.proto, tools/mcsema_disass/ida/exception.py, tools/mcsema_disass/ida/flow.py, tools/mcsema_disass/ida/get_cfg.py, tools/mcsema_disass/ida/refs.py, tools/mcsema_disass/ida/util.py
=> Parsing eh_frame and language specific data area.

mcsema/Arch/X86/Runtime/Runtime.cpp
Definition of atomic intrinsics required to support atomic instructions.
=> Atomic intrinsic support

tools/mcsema_disass/ida/exception.py
The argumentation string is not recoverable from eh frames. Skip CIE entry in such cases.
=> Issue 377 missing augmentation string

tests/test_suite/start.py
* Stop using /tmp to store files
* More verbose output about what is being executed so its easier to
debug test failures
=> Integration tests work on multiuser systems

tools/mcsema_lift/Lift.cpp
=> Show usage message for `mcsema-lift`

mcsema/Arch/X86/Runtime/Runtime.cpp
Adds DRx and CRx registers that are present in remill.
=> Add debug and CR registers present in remill

mcsema/BC/Segment.cpp
=> Deduce libc ctor/dtor based on functions in cfg

mcsema/CFG/CFG.proto
=> Issue 136 cfg documentation

scripts/lift_directory.py, scripts/lift_program.py
Also adds `--extra_args` to be passed to the `mcsema-lift`.
=> Add Binja Disassmbler Support

mcsema/BC/Function.cpp
=> Devirtualization can only happen in read_only segment

.gitignore, .travis.yml, scripts/.gitignore, scripts/travis.sh, scripts/update_binja.py
* Install and verify that Binary Ninja will run in Travis-CI
=> Initial attempt at running Binary Ninja in CI instances

tools/mcsema_disass/binja/vars.py
Fixes a typo
Fixes API compatibility in Binja dev channel
Somehow resolves whatever I was trying to vocalize in #479
=> Fixes Change in API

tests/MakingTests.md, tests/test_suite_generator/CMakeLists.txt
Fixes #491 
* Update CMakeLists to look for idat64 (IDA 7+)
* Update documentation
=> Fix Issue #491

README.md, tools/Dockerfile
=> Added Dockerfile

tools/mcsema_disass/ida/binja_var_recovery/il_analysis.py, tools/mcsema_disass/ida/binja_var_recovery/il_function.py, tools/mcsema_disass/ida/binja_var_recovery/il_instructions.py, tools/mcsema_disass/ida/binja_var_recovery/il_variable.py, tools/mcsema_disass/ida/binja_var_recovery/util.py, tools/mcsema_disass/ida/variable_analysis_binja.py
* Merge LLIL variable recovery for deliverable
=> Use LLIL for Variable Recovery

tools/mcsema_disass/ida7/collect_variable.py
Fix the sign conversion which is causing the problem with IDA 7.1
=> Issue501 stack variable recovery

README.md
according to https://engineering.avast.io/retdec-v4-0-is-out/
=> adjusted readme to retdec update

mcsema/Arch/ABI.cpp
* explicitly cast TypeSize arguments to uint64_t
=> Support LLVM 10

.github/workflows/ci.yml, Dockerfile, README.md
In progress to solve issue #689 
closes #689
=> Update docs and fix docker mcsema-disass

mcsema/Arch/X86/Runtime/CMakeLists.txt
=> Disable building any 32-bit runtimes.

Dockerfile
Closes #722 
* Update python 2.7 pip install script location
=> Fix python2.7 paths due to Py2.7 EOL

CMakeLists_vcpkg.txt, cmake/BCCompiler.cmake, cmake/vcpkg_helper.cmake, mcsema/Version/CMakeLists.txt
Required for https://github.com/trailofbits/cxx-common/pull/677 and https://github.com/trailofbits/cxx-common/pull/679
=> vcpkg: Support Windows and arm64

.github/workflows/ci.yml, .github/workflows/vcpkg_ci.yml, mcsema/BC/Function.cpp, mcsema/BC/Optimize.cpp, scripts/docker-lifter-entrypoint.sh, tools/mcsema_lift/Lift.cpp
Should at least build 🤞 
First stab at trying for backwards compatibility.
closes #728
=> Support LLVM 11

.github/workflows/docker.yml, Dockerfile
=> Fix Dockerfile and add to CI

scripts/show_cfg.py
to use this , you have to put the CFG_pb2.py file, which from the  mcsema/tools/mcsema_disass/ida7/ , into the same dir as this script
type  python show_cfg.py "xxx.cfg" "xxx.txt" 
the first arg is the location of the cfg file you want to see, like "./maze.cfg"
the second arg is the location of the generated cfg details if the cfg file, like "./cfgdetails.txt"
=> a simple scripts to show the details in a cfg file
