- .gitignore
- mc-sema/CMakeLists.txt
- mc-sema/cmake/modules/FindPin.cmake
- mc-sema/validator/CMakeLists.txt
cmake 2.8 does not support URL_HASH, only URL_MD5.
> mc-sema: fix Pin download on cmake 2.8

- mc-sema/CMakeLists.txt
I made a little mistake in my previous PR: CMake always uses the second argument of "option" as the description, not the default value, so here the description ended being "ON":
`option(MCSEMA_ENABLE_PIN_VALIDATOR ON)`
I set the default value to OFF now since most people won't need Pin anyway.
> Fix description of MCSEMA_ENABLE_PIN_VALIDATOR option

- mcsema/cfgToLLVM/x86Instrs_MOV.cpp
Need this to cover:
.text
movl	$4294967288, %edx       # <MCInst #1662 MOV32ri_alt
Which previously would just error out as an unlifted instruction
> making the MOV32ri handler work for MOV32ri_alt as well

- .gitignore
- README.md
- bootstrap.sh
- mcsema/cfgToLLVM/x86Helpers.cpp
- mcsema/cfgToLLVM/x86Instrs.cpp
- mcsema/cfgToLLVM/x86Instrs_Branches.cpp
- mcsema/cfgToLLVM/x86Instrs_CMOV.cpp
- mcsema/cfgToLLVM/x86Instrs_Jcc.cpp
- mcsema/cfgToLLVM/x86Instrs_Misc.cpp
- mcsema/cfgToLLVM/x86Instrs_Stack.cpp
- mcsema/cfgToLLVM/x86Instrs_bitops.cpp
- mcsema/cfgToLLVM/x86_64Helpers.cpp
* Do not install mcsema for all users
* Use `nprocs` to figure out how many CPUs we have instead of hardcoding 4
> Bootstrap fixes

- mcsema/cfgToLLVM/x86Instrs_MOV.cpp
* Use `IMM_AS_DATA_REF<32>` in MOV32mi, which will always write a 32-bit value. This would cause assertions in StoreInst on amd64 when the code was hit.
> Use 32-bit values when doing 32-bit memory moves

- mcsema/Arch/Arch.cpp
- tools/mcsema_disass/defs/linux.txt
* Remove an unused entry for __gmon_start__ for linux defs
* Pass the linkage type to the arch specific driver generation
> Fix weak symbol support

- tools/mcsema_disass/__main__.py
- tools/mcsema_disass/ida/disass.py
Closes #149 #148 #145 
* Documents `--pie-mode` and `--std_defs`
* Checks that a CFG was generated
* Makes `--entrypoint` required
> Fix disass checks

- mcsema/Arch/Arch.h
- mcsema/CFG/CFG.h
Just added ifdefs:
#ifdef __x86_64__
typedef uint64_t VA;
#else
typedef uintptr_t VA;
#endif
Hopefully that's how you guys check for 64-bit/32-bitness
> minor fix: typedef of VA makes compilation on 32-bit machines fail

- CMakeLists.txt
- bootstrap.bat
- mcsema/Arch/X86/Runtime/State.h
- mcsema/Arch/X86/Semantics/SSE.cpp
- mcsema/BC/Util.h
* Lower build requirements to Win7 and VS2013 (sorry, `constexpr`)
* Disable lots of unneeded warnings in LLVM code that we trigger by linking to it
* Remove dependencies on wget, automatically install 7zip
* Use cmake --build instead of msbuild
* Fix asm file generation
> Windows bootstrap fixes

- tests/linux/amd64/config.json
- tests/linux/amd64/expected_outputs.json
Add integration tests for ls `ls --recursive`. I used the backticks in my commit message in the shell, so the commit message is nice and crazy.
> Add integration tests for `ls --recursive`

- mcsema/Arch/X86/Util.cpp
Previously `MEM_REFERENCE()` would be called if an instruction had external refs, but MEM_REFERENCE would not do anything with externals. It *did* sanity check that the instruction had a `mem_reference` and threw an error otherwise, which helped find this bug.
> Fix MEM_REFERENCE to read externals

- CMakeLists.txt
The CMAKE_CXX_STANDARD switch is not recognised before CMake 3.1. Hence, the build is broken when attempting to use CMake 2.8.1, as I did.
This change inhibits the usage of too old CMake.
> Requiring CMake 3.1 to make CMAKE_CXX_STANDARD switch effective

- bootstrap.sh
I've edited the bootstrap script to make it work on my system (Arch Linux).
Other changes:
1. Added a couple of sanity checks to avoid breaking the script when something goes wrong (i.e.: when you get a broken llvm src tarball).
2. Always attempt to continue if the required packages could not be installed, informing the user to make sure that the needed libraries are correctly installed.
3. The bootstrap.osx.sh steps have been merged.
I couldn't test the OSX steps as I don't have a Mac system.
> Unify the bootstrap shellscripts into one. Add support to Arch Linux, Ubuntu and OSX.

- tools/mcsema_disass/ida/get_cfg.py
The disassembler script can now be run manually from
IDA Pro (File, Script file...). The 'ida_kernwin.cvar.batch'
variable is used to determine whether IDA Pro is being run
in batch mode or not.
> The disassembler script (get_cfg.py) can now be run manually.

- mcsema/Arch/X86/Semantics/Misc.cpp
I think all I had to do to fix it is to change the CreateLShr to CreateShl (as in BTSrr).  Hopefully I'm right, but needs more testing.  Works with my examples though.
> fixing BTSmr, basically just changing the LShr to Shl

- mcsema/Arch/X86/Semantics/Stack.cpp
On x86_64, imm8 pushes lead to 64bit sign extension of the operand. Hence, instructions such as
6a 00       push 0x0
decrement rsp by 8. However, prior to this fix, mcsema created a 4 byte decrement, leading to stack corruption. Consequently, when lifting the ls.cfg example and compiling back, the resulting binary crashes when invoked with the --version parameter.
> Sign-extend imm8 push operands to 64 bit on x86_64.

- mcsema/Arch/X86/Runtime/CallingConv.cpp
- mcsema/Arch/X86/Runtime/CallingConv.h
- mcsema/BC/Callback.cpp
- mcsema/BC/External.cpp
- mcsema/BC/External.h
- mcsema/BC/Function.cpp
- mcsema/CFG/CFG.cpp
- mcsema/CFG/CFG.h
- tools/mcsema_disass/ida/refs.py
Bitcode generated with --explicit-args argument now has, for external function calls, calls to retrieve each argument according to calling convention. Still WIP.
> Explicit args [WIP]

- tools/mcsema_disass/ida/get_cfg.py
Jump tables on amd64 may use >32bit VAs
> Fix jump tables on amd64

- mcsema/BC/Callback.cpp
lllvm::GEPOperator::accumulateConstantOffset(datalayout, offset) fail an assert if the width of the offset (type: APInt) does not match the size of a pointer in bits for the target.  See:
https://github.com/llvm-mirror/llvm/blob/release_40/lib/IR/Operator.cpp#L23-L25
The above assert fails when I try to lift a 32-bit binary.
Making the width of offset = dl.getPointerSizeInBits() allows me to lift the binary succesfully.
> accumulate gep offset in value of width ptr size

- docs/McsemaWalkthrough.md
- tools/mcsema_disass/binja/util.py
- tools/setup.py
Hey McSema folks!
Just some minor fixes that I made when experimenting with McSema yesterday. This includes:
* Some updates to the walk through (removing a non-existent command-line option)
* Added an `install_requires` for Python dependencies
* I had errors in the Binary Ninja disassembler when `bv.read` returned less than the number of bytes requested. I added some code to pad the returned string if required. The padding is dependent on the endianness.
Please let me know your thoughts!
> Some minor fixes

- mcsema/Arch/ABI.cpp
- mcsema/BC/External.cpp
- tools/mcsema_disass/ida/get_cfg.py
- tools/mcsema_disass/ida/util.py
- tools/mcsema_lift/Lift.cpp
This branch fixes a parity issue where calls to externals via thunks were lifted as calls to the lifted thunks, as opposed to going through "faster" mechanisms (e.g. wrapping the externals directly). This affected both static analysis, and quality of recompiled lifted bitcode.
> Thunk resolution

- tools/mcsema_lift/Lift.cpp
Addressing #314 
Please disregard the whitespace changes; it's just the result of the `clang-format`.
> Bring back the mcsema-lift option for --list-supported

- tools/mcsema_disass/ida/exception.py
We are only interested in catch and cleanup type of actions and not in the catch typeinfo. The lifter defines all catch passthrough as null type.
> issue #370: qpdfview crashes due to different catch types

- tools/mcsema_lift/Lift.cpp
Support multiple ABI libraries on the commandline
* Flag name from `abi_library` -> `abi_libraries`
* Load a comma separated list of different ABI libraries
> Suport multiple ABI libraries on command line

- mcsema/OS/Linux/ABI_exceptions.cpp
- tools/mcsema_disass/defs/linux.txt
The exit function fails during the destruction of `ios_base` derived objects.
> Missing ios_base destructor

- CMakeLists.txt
The libc ABI file should be generated for MacOS and included in `OS/macos` path. Check for the OS type before including directory.
> Issue 423 libc abi macos

- mcsema/OS/Linux/ABI_libc.c
* Put a compile-time guard around amd64 specific function definitions
When remill #269 (https://github.com/trailofbits/remill/pull/269) is merged, this will close #442
> Guard amd64 specific function calls in ABI_libc

- tools/mcsema_disass/ida/util.py
Assign the default personality if the instruction is NoneType or there is AttributeError.
> Handle attribute error on instruction personality check

- CMakeLists.txt
- scripts/travis.sh
By default, all ABI libraries are disabled.
To skip the 'Linux' ABI library:
cmake -DMCSEMA_DISABLED_ABI_LIBRARIES:STRING="Linux"
> Add a new CMake variable to enable/disable ABI libraries

- mcsema/OS/Linux/ABI_libc.h
* Removes ultrasound.h form ABI_libc.h as it only defines macros and is not present on newer systems
> Remove a header from ABI_libc.h

- tools/mcsema_disass/__main__.py
* Pass --std-defs to downstream scripts instead of eating it in __main__.py. Without this, only the default definitions file ever gets loaded.
> Make --std-defs work again for mcsema-disass

- mcsema/BC/External.cpp
- tools/mcsema_disass/ida7/get_cfg.py
Treat large external variables are arrays of bytes and not big integers.
Fixes #500
> Treat large externals as byte arrays and not big integers

- mcsema/BC/Function.cpp
- mcsema/CFG/CFG.cpp
- mcsema/CFG/CFG.h
`NativeFunction` `function` attribute is now properly set in case someone will need to use it.
There are some codestyle changes as well, `Native` family has now proper default inicialization.
> Native function improvements

- mcsema/BC/Segment.cpp
- mcsema/CFG/CFG.cpp
The lazy initialization fails because the xref variable is not resolved. Instead of using the lazy initialization, truncate and statically assign it.
> Check for the xref variable before calling lazy init

- mcsema/BC/Callback.cpp
- mcsema/BC/Segment.cpp
Fix of #547 and #546 
Replaces
`@llvm.global_ctors = appending constant` 
with
`@llvm.global_ctors = appending global`
which should be the more correct way.
> Various fixes

- README.md
[ios-analysis-dagger](https://github.com/IAIK/ios-analysis-dagger/) is a fork (actually a copy) of dagger with extended support for aarch64.
This PR updates the tool comparison table in README.md with aarch64 support for dagger.
> Add ios-analysis-dagger to tool comparison in README.md

- mcsema/CFG/CFG.cpp
CFG files that do not contain `.text` should be lifted without assertion error.
Excluding `.text` section can theoretically lead to some problems, but since McSema is focused on binaries produced by a sane compiler, this should not be a concern.
> Remove required code section

- README.md
* realpath is a package that does not exist in modern Linux as it is part of the base system, hence the apt install command fails then
* I had to build mcsema twice because dyninst details are on a different page. So I moved and added explanation to the building part on the main page.
hope thats fine
> earlier dyninst mentioning and realpath fix

- tools/mcsema_disass/ida7/get_cfg.py
In issues #614 , IDA 7.4 cannot recognize function `GetTrueName` and eventually resulting error:
```
'module' object has no attribute 'GetTrueName' error
```
The solution is fairly simple, remove `idc.GetTrueName(ea)` and IDA 7.4 can run correctly.
> remove deprecated function `idc.GetTrueName(ea)` to support IDA7.4

- tools/mcsema_disass/ida7/segment.py
- tools/mcsema_disass/ida7/table.py
Several APIs in original IDA7 backend are deprecated(still IDA6+ version).
This fix adapts those change according to [SDK porting guide](https://www.hex-rays.com/products/ida/7.0/docs/api70_porting_guide.shtml)
> Migrate IDA7 backend to latest API

- mcsema/BC/Function.cpp
In some case the `seg` might be NULL pointer.
We have to add an additional check to fallback otherwise crash will happen.
> Additional check to prevent null target_segment

- cmake/settings.cmake
Update c++ standard to `C++17`.
Having modern c++ brings a lot of benefits to the codebase and it is not even that unreasonably new, as `C++20` is being implemented.
`CFG_format_update` and possibly other branches are already counting with this change. It is presented in separate PR so it can be easily found as a commit in master.
> cmake: Set c++ standard to c++17.

- tools/mcsema_disass/binja/cfg.py
The key look-up assumes proper string conversion to "cdecl" which appears to not be the case on the latest Binary Ninja development build, thus: `KeyError: <calling convention: aarch64 cdecl>` occurs. By coercing to a string, this issue is fixed.
> Fix KeyError issue with AArch64 targets

- mcsema/BC/Function.cpp
- mcsema/BC/Optimize.cpp
- tools/mcsema_disass/ida7/flow.py
- tools/mcsema_disass/ida7/get_cfg.py
- tools/mcsema_disass/ida7/util.py
What would happen is that AL/AH, DL/DH, etc. would all map to the same alias because their containing register and types would be the same. Modified register aliases to have the form <name>_<offset>_<type>. Also fixed an issue in mcsema-disass where the main function wouldn't be recognized as a function, and thus not lifted.
> Fixes one egregious bug in how we alias registers.

- .github/workflows/vcpkg_ci.yml
Seems the MacOS CI runners have changed some logic underneath us, so these smoketests were failing.
> MacOS CI: Fix Python tool test with PYTHONPATH

- .github/workflows/ci.yml
- Dockerfile
Had to rename the directory where the Python 3 module is installed so that we could hard-code the PYTHONPATH to it, e.g. `lib/python3.6` -> `lib/python3` on Ubuntu 18.04 with default Python version installed by `apt install python3` or `lib/python3.8` -> `lib/python3` for Ubuntu 20.04.
closes #730
> Remove Python2 from pushed Docker images

- CMakeLists_vcpkg.txt
Anvill now installs unversioned target
> Fix anvill install target usage

- .github/workflows/vcpkg_ci.yml
- mcsema/BC/Optimize.cpp
**DO NOT MERGE** Waiting for remill fixes branch to be merged into `master`
Add some smoketests to CI
> Fix bad LoadInst compat for LLVM 11

- README.md
Updated instructions for building with LLVM versions 9, 10, 11 and 12.
Since it is confusing for first readers to build `mcsema`, this commit will clarify readers on the steps of building it. This is needed as users might encounter errors such as [this](https://githubmemory.com/repo/lifting-bits/mcsema/issues/750) which I encountered myself for LLVM version 12.
> Updated README.md to build with LLVM versions

- tools/mcsema_disass/ida7/disass.py
This is a pertaining issue in Linux systems where the DISPLAY variable isn't forwarded.
The error which is fixed is; "QXcbConnection: Could not connect to display". Users before have raised issues on this [here](https://github.com/lifting-bits/mcsema/issues?q=QXcbConnection%3A+Could+not+connect+to+display)
> Fixed "could not connect to display" error
